auto_download: true
coco_root: ./datasets/coco
exp_defaults: mamba_results

# Set these if the dataset is already downloaded, and comment out coco_root
# Set auto_download = false
# train_root: /dataset/coco/train2017
# val_root:   /dataset/coco/val2017
# ann_root:   /dataset/coco/annotations

# training
epochs: 4
batch_size: 1            # per-GPU
train_max_items: 2000
train_subset_seed: 1337
val_batch_size: 1
val_max_items: 64        # cap number of validation images (0 = no cap)
val_subset_seed: 1337    # seed for deterministic val subset sampling
grad_accum: 4            # effective 8

# Hyperparameters
lr: 2.0e-4
min_lr: 5.0e-6
weight_decay: 0.005
ema_decay: 0.999
warmup_steps: 1500
amp: true

# Saving
save_every: 2000
val_every: 1000
panel_every: 200
log_every: 100

# dataloader
num_workers: 16
num_workers_val: 16
prefetch_factor: 2

# loss weights
lambda_l1: 0.1
lambda_lpips: 0.8
lambda_uv: 6.7        # starting weight for chroma loss

# aug
crop_size: 256
hflip: true
rgb_jitter_prob: 0.3
rgb_jitter_strength: 0.15

# model
model:
  variant: MambaIRv2    # for logging only
  upscale: 1
  in_chans: 3
  img_size: 256
  img_range: 1.
  embed_dim: 174
  d_state: 16
  depths: [6,6,6,6,6,6]
  num_heads: [6,6,6,6,6,6]
  window_size: 16
  inner_rank: 64
  num_tokens: 128
  convffn_kernel_size: 5
  mlp_ratio: 2.

# ckpt
pretrained: checkpoints/mambairv2_ColorDN_15.pth
resume: null

# LPIPS downsample
lpips_side: 256