auto_download: true
coco_root: ./datasets/coco
exp_defaults: mamba_results

# Set these if the dataset is already downloaded, and comment out coco_root
# Set auto_download = false
# train_root: /dataset/coco/train2017
# val_root:   /dataset/coco/val2017
# ann_root:   /dataset/coco/annotations

# training
epochs: 30
batch_size: 8            # per-GPU
grad_accum: 2            # effective 16
lr: 2.0e-4
weight_decay: 0.05
warmup_steps: 1000
amp: true
ema_decay: 0.999
num_workers: 8
save_every: 2000
val_every: 1000

# loss weights
lambda_l1: 1.0
lambda_lpips: 0.2

# aug
crop_size: 256
hflip: true
rgb_jitter_prob: 0.2
rgb_jitter_strength: 0.1

# model
model:
  variant: MambaIRv2    # for logging only
  embed_dim: 174
  depths: [4,4,6,4]
  num_heads: [6,6,6,6]

# ckpt
pretrained: checkpoints/mambairv2_ColorDN_15.pth
resume: null